### ISSUE TITLE
trash and ram-disk

### ISSUE THREAD

**Issue by grylem** [LdBeth/trash#1]
Hi.
make ram-disk & cd to
touch file
trash file
trash -l
does not show files in trash bin.

Maybe you can also make your 'trash' look more like rm?
trash -I file   # remove without confirmation
trash directory_name   # remove without warning etc.

Regards.

**Comment by LdBeth** [comment]
> does not show files in trash bin.

The file inside a ramdisk (or any other kind of mounted volumes) are trashed to /Volumes/[ramdisk]/.Trashes/[uid]/, and unfortunately sudo is required to access that directory. It is only possible to get that via AppleScript or SBApplication (which is the method ObjC trash used). Last time I checked it was not easy to do the SBApplication way with swift, but seems it is feasible now.

> Maybe you can also make your 'trash' look more like rm?

I'll add the `-i` switch, but I'll not change the behavior trashing a directory.

**Comment by LdBeth** [comment]
The changes are push to the repo.
